In [29]:
import pandas as pd
import jenkspy

In [30]:
# -*- coding: utf-8 -*-
# @Desc    : natural break jenk classification of influencing factors

excel_path = r"final_ZCTA.xlsx"
class_type = 5 
out_path = r"NYC_break.xlsx"

ret = {
    }
df = pd.read_excel(excel_path)
for col_name in df:
    col = df[col_name]
    breaks = jenkspy.jenks_breaks(col, nb_class=class_type) 
    ret[col_name] = breaks

out_df = pd.DataFrame(ret)
#out_df.to_excel(out_path)

In [31]:
out_df

,MedInc,MedAge,Per_White,Per_Bach,Per_Public,pop_den,transit_den,non_transit_den,stop_den,hosp_den,access_MEAN,PERCENT_PO
0,15966.0,27.7,0.024178,0.042352,0.119254,533.0,0.000000,9.089521,0.000000,0.000000,2.060605,6.61
1,26429.0,33.2,0.186659,0.088375,0.336259,9794.0,13.804309,29.460581,4.421898,0.758414,5.229156,12.75
2,38073.0,37.0,0.348702,0.135978,0.469577,18565.0,27.642081,40.497721,16.647955,1.968226,7.511566,17.69
3,59847.0,40.7,0.513823,0.195920,0.585710,28406.0,51.262895,52.716124,21.985199,3.689141,10.041382,22.25
4,92414.0,44.9,0.701514,0.276272,0.685221,38375.0,93.892561,69.369920,26.023684,5.464596,13.171548,26.43
5,143068.0,50.8,0.949918,0.405970,0.867751,57511.0,162.524017,105.419899,30.462227,7.900563,16.663091,32.53

In [32]:
pop_den=out_df['pop_den'].tolist()
MedInc=out_df['MedInc'].tolist()
MedAge=out_df['MedAge'].tolist()
Per_White=out_df['Per_White'].tolist()
Per_Bach=out_df['Per_Bach'].tolist()
Per_Public=out_df['Per_Public'].tolist()
positive=out_df['PERCENT_PO'].tolist()
hosp_den=out_df['hosp_den'].tolist()
transit_den=out_df['transit_den'].tolist()
non_transit_den=out_df['non_transit_den'].tolist()
stop_den=out_df['stop_den'].tolist()

In [35]:
data = pd.read_excel('final_ZCTA.xlsx')

In [37]:
data['pop_den_label']=pd.cut(x=data['pop_den'],bins=pop_den,labels=[1,2,3,4,5])
data['MedInc_label']=pd.cut(x=data['MedInc'],bins=MedInc,labels=[1,2,3,4,5])
data['MedAge_label']=pd.cut(x=data['MedAge'],bins=MedAge,labels=[1,2,3,4,5])
data['Per_White_label']=pd.cut(x=data['Per_White'],bins=Per_White,labels=[1,2,3,4,5])
data['Per_Bach_label']=pd.cut(x=data['Per_Bach'],bins=Per_Bach,labels=[1,2,3,4,5])
data['Per_Public_label']=pd.cut(x=data['Per_Public'],bins=Per_Public,labels=[1,2,3,4,5])
data['pos_label']=pd.cut(x=data['PERCENT_PO'],bins=positive,labels=[1,2,3,4,5])
data['hosp_den_label']=pd.cut(x=data['hosp_den'],bins=hosp_den,labels=[1,2,3,4,5])
data['transit_den_label']=pd.cut(x=data['transit_den'],bins=transit_den,labels=[1,2,3,4,5])
data['non_transit_den_label']=pd.cut(x=data['non_transit_den'],bins=non_transit_den,labels=[1,2,3,4,5])
data['stop_den_label']=pd.cut(x=data['stop_den'],bins=stop_den,labels=[1,2,3,4,5])

In [38]:
data.head()

,MedInc,MedAge,Per_White,Per_Bach,Per_Public,pop_den,transit_den,non_transit_den,stop_den,hosp_den,...,MedInc_label,MedAge_label,Per_White_label,Per_Bach_label,Per_Public_label,pos_label,hosp_den_label,transit_den_label,non_transit_den_label,stop_den_label
0,65099,36.9,0.650039,0.313472,0.501394,14089,42.235791,37.663186,29.209522,3.505143,...,4,2,4,5,3,1,3,3,2,5
1,20577,44.3,0.320211,0.177339,0.531444,32673,29.865434,61.247392,28.953325,4.386867,...,1,4,2,3,3,3,4,3,4,5
2,70241,32.5,0.753673,0.303351,0.524662,36053,60.254776,67.132579,29.389187,3.339680,...,4,1,5,5,3,2,3,4,4,5
3,107637,37.4,0.609595,0.380510,0.510067,8737,155.731830,96.459745,28.816483,2.619680,...,5,3,4,5,3,1,3,5,5,5
4,103909,30.3,0.750718,0.378003,0.624243,45035,162.524017,105.419899,25.879042,5.175808,...,5,1,5,5,4,2,4,5,5,4

In [40]:
data.to_csv('natural.csv')

In [47]:
#quantile
pop_den_q=[533,5913,11562,17934,27401,57512]
MedInc_q=[0,25698,31191,38073,53642,143068]
MedAge_q=[0,34.1,36.1,38.9,41.7,50.8]
per_bach_q=[0,0.103904,0.135978,0.162942, 0.259018,1]
per_white_q=[0,0.178509,0.371859,0.573185,0.718825,1]
per_public_q=[0,0.396349,0.504857,0.584849,0.671882,1]
pos_q=[6.6,16.6,21.31,23.14,24.63,32.53]
stop_den_q=[0,24.921715,27.644617,28.086387,28.598620,30.462227]
tran_den_q=[0,10.206557,19.441615,25.723687,38.891029,163]
non_tran_q=[0,30.020964,34.502288,37.611502,44.536176,106]
hosp_den_q=[0,0.244823,0.642613,1.303493,3.135671,7.900563]

In [42]:
#geometric interval
pop_den_g=[533,7716,11543,18726,32208,57511]
MedInc_g=[0,26949.660611,31221.263337,42204.923947,70447.438094,151316.000000]
MedAge_g=[0,34.893858,38.397034,40.102966,43.606142,51]
per_bach_g=[0,0.101148,0.142178,0.200974,0.285230,1]
per_white_g=[0,0.177599,0.345460,0.529119,0.730063,1]
per_public_g=[0,0.327672,0.454757,0.532247,0.659332,1]
pos_g=[6.6,15.459262,18.900787,20.239213,23.680738,32.530000]
stop_den_g=[0,19.864721,26.034504,27.950778, 28.545953,31]
tran_den_g=[0,15.780862,22.495722,38.276583,75.363819,163]
non_tran_g=[0,24.665951,35.535661,51.112091,73.433310,106]
hosp_den_g=[0,0.270204, 0.800674,1.842104,3.886657,8]

In [43]:
#equal interval
pop_den_e=[533,11929,23324,34720,46115,57511]
MedInc_e=[0,41386.400000,66806.800000,92227.200000,117647.600000,151316.000000]
MedAge_e=[0,32.320000,36.940000,41.560000,46.18,82.100000]
per_bach_e=[0,0.115076,0.187799,0.260523,0.333246,1]
per_white_e=[0,0.209326,0.394474,0.579622,0.764770,1]
per_public_e=[0,0.268953, 0.418653,0.568352,0.718051,1]
pos_e=[6.6,11.794000,16.978000, 22.162000,27.346000,32.53]
stop_den_e=[0,6.092445,12.184891,18.277336,24.369781,31]
tran_den_e=[0,32.504803,65.009607,97.514410,130.019214,163]
non_tran_e=[0,28.355597,47.621672,66.887748,86.153823,106]
hosp_den_e=[0,1.580113,3.160225,4.740338, 6.320451,8]

In [48]:
#define quantile
data['pop_den_label']=pd.cut(x=data['pop_den'],bins=pop_den_q,labels=[1,2,3,4,5])
data['MedInc_label']=pd.cut(x=data['MedInc'],bins=MedInc_q,labels=[1,2,3,4,5])
data['MedAge_label']=pd.cut(x=data['MedAge'],bins=MedAge_q,labels=[1,2,3,4,5])
data['Per_White_label']=pd.cut(x=data['Per_White'],bins=per_white_q,labels=[1,2,3,4,5])
data['Per_Bach_label']=pd.cut(x=data['Per_Bach'],bins=per_bach_q,labels=[1,2,3,4,5])
data['Per_Public_label']=pd.cut(x=data['Per_Public'],bins=per_public_q,labels=[1,2,3,4,5])
data['pos_label']=pd.cut(x=data['PERCENT_PO'],bins=pos_q,labels=[1,2,3,4,5])
data['hosp_den_label']=pd.cut(x=data['hosp_den'],bins=hosp_den_q,labels=[1,2,3,4,5])
data['transit_den_label']=pd.cut(x=data['transit_den'],bins=tran_den_q,labels=[1,2,3,4,5])
data['non_transit_den_label']=pd.cut(x=data['non_transit_den'],bins=non_tran_q,labels=[1,2,3,4,5])
data['stop_den_label']=pd.cut(x=data['stop_den'],bins=stop_den_q,labels=[1,2,3,4,5])

In [49]:
data.head()

,MedInc,MedAge,Per_White,Per_Bach,Per_Public,pop_den,transit_den,non_transit_den,stop_den,hosp_den,...,MedInc_label,MedAge_label,Per_White_label,Per_Bach_label,Per_Public_label,pos_label,hosp_den_label,transit_den_label,non_transit_den_label,stop_den_label
0,65099,36.9,0.650039,0.313472,0.501394,14089,42.235791,37.663186,29.209522,3.505143,...,5,3,4,5,2,1,5,5,4,5
1,20577,44.3,0.320211,0.177339,0.531444,32673,29.865434,61.247392,28.953325,4.386867,...,1,5,2,4,3,2,5,4,5,5
2,70241,32.5,0.753673,0.303351,0.524662,36053,60.254776,67.132579,29.389187,3.339680,...,5,1,5,5,3,1,5,5,5,5
3,107637,37.4,0.609595,0.380510,0.510067,8737,155.731830,96.459745,28.816483,2.619680,...,5,3,4,5,3,1,4,5,5,5
4,103909,30.3,0.750718,0.378003,0.624243,45035,162.524017,105.419899,25.879042,5.175808,...,5,1,5,5,4,1,5,5,5,2

In [50]:
data.to_csv('quantile.csv')

In [52]:
#define geometric interval
data['pop_den_label']=pd.cut(x=data['pop_den'],bins=pop_den_g,labels=[1,2,3,4,5])
data['MedInc_label']=pd.cut(x=data['MedInc'],bins=MedInc_g,labels=[1,2,3,4,5])
data['MedAge_label']=pd.cut(x=data['MedAge'],bins=MedAge_g,labels=[1,2,3,4,5])
data['Per_White_label']=pd.cut(x=data['Per_White'],bins=per_white_g,labels=[1,2,3,4,5])
data['Per_Bach_label']=pd.cut(x=data['Per_Bach'],bins=per_bach_g,labels=[1,2,3,4,5])
data['Per_Public_label']=pd.cut(x=data['Per_Public'],bins=per_public_g,labels=[1,2,3,4,5])
data['pos_label']=pd.cut(x=data['PERCENT_PO'],bins=pos_g,labels=[1,2,3,4,5])
data['hosp_den_label']=pd.cut(x=data['hosp_den'],bins=hosp_den_g,labels=[1,2,3,4,5])
data['transit_den_label']=pd.cut(x=data['transit_den'],bins=tran_den_g,labels=[1,2,3,4,5])
data['non_transit_den_label']=pd.cut(x=data['non_transit_den'],bins=non_tran_g,labels=[1,2,3,4,5])
data['stop_den_label']=pd.cut(x=data['stop_den'],bins=stop_den_g,labels=[1,2,3,4,5])

In [53]:
data.head()

,MedInc,MedAge,Per_White,Per_Bach,Per_Public,pop_den,transit_den,non_transit_den,stop_den,hosp_den,...,MedInc_label,MedAge_label,Per_White_label,Per_Bach_label,Per_Public_label,pos_label,hosp_den_label,transit_den_label,non_transit_den_label,stop_den_label
0,65099,36.9,0.650039,0.313472,0.501394,14089,42.235791,37.663186,29.209522,3.505143,...,4,2,4,5,3,1,4,4,3,5
1,20577,44.3,0.320211,0.177339,0.531444,32673,29.865434,61.247392,28.953325,4.386867,...,1,5,2,3,3,3,5,3,4,5
2,70241,32.5,0.753673,0.303351,0.524662,36053,60.254776,67.132579,29.389187,3.339680,...,4,1,5,5,3,1,4,4,4,5
3,107637,37.4,0.609595,0.380510,0.510067,8737,155.731830,96.459745,28.816483,2.619680,...,5,2,4,5,3,1,4,5,5,5
4,103909,30.3,0.750718,0.378003,0.624243,45035,162.524017,105.419899,25.879042,5.175808,...,5,1,5,5,4,1,5,5,5,2

In [54]:
data.to_csv('geometric.csv')

In [56]:
#define equal interval
data['MedInc_label']=pd.cut(x=data['MedInc'],bins=MedInc_q,labels=[1,2,3,4,5])
data['MedAge_label']=pd.cut(x=data['MedAge'],bins=MedAge_q,labels=[1,2,3,4,5])
data['Per_White_label']=pd.cut(x=data['Per_White'],bins=per_white_q,labels=[1,2,3,4,5])
data['Per_Bach_label']=pd.cut(x=data['Per_Bach'],bins=per_bach_q,labels=[1,2,3,4,5])
data['Per_Public_label']=pd.cut(x=data['Per_Public'],bins=per_public_q,labels=[1,2,3,4,5])
data['pop_den_label']=pd.cut(x=data['pop_den'],bins=pop_den_e,labels=[1,2,3,4,5])
data['pos_label']=pd.cut(x=data['PERCENT_PO'],bins=pos_e,labels=[1,2,3,4,5])
data['hosp_den_label']=pd.cut(x=data['hosp_den'],bins=hosp_den_e,labels=[1,2,3,4,5])
data['transit_den_label']=pd.cut(x=data['transit_den'],bins=tran_den_e,labels=[1,2,3,4,5])
data['non_transit_den_label']=pd.cut(x=data['non_transit_den'],bins=non_tran_e,labels=[1,2,3,4,5])
data['stop_den_label']=pd.cut(x=data['stop_den'],bins=stop_den_e,labels=[1,2,3,4,5])

In [57]:
data.head()

,MedInc,MedAge,Per_White,Per_Bach,Per_Public,pop_den,transit_den,non_transit_den,stop_den,hosp_den,...,MedInc_label,MedAge_label,Per_White_label,Per_Bach_label,Per_Public_label,pos_label,hosp_den_label,transit_den_label,non_transit_den_label,stop_den_label
0,65099,36.9,0.650039,0.313472,0.501394,14089,42.235791,37.663186,29.209522,3.505143,...,5,3,4,5,2,1,3,2,2,5
1,20577,44.3,0.320211,0.177339,0.531444,32673,29.865434,61.247392,28.953325,4.386867,...,1,5,2,4,3,3,3,1,3,5
2,70241,32.5,0.753673,0.303351,0.524662,36053,60.254776,67.132579,29.389187,3.339680,...,5,1,5,5,3,2,3,2,4,5
3,107637,37.4,0.609595,0.380510,0.510067,8737,155.731830,96.459745,28.816483,2.619680,...,5,3,4,5,3,1,2,5,5,5
4,103909,30.3,0.750718,0.378003,0.624243,45035,162.524017,105.419899,25.879042,5.175808,...,5,1,5,5,4,2,4,5,5,5

In [58]:
data.to_csv('equal.csv')